/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2017-02-20 15:30:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"fr\" >\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<!-- Ce site a été créé avec http://www.creer-son-website.fr/ -->\r\n");
      out.write("\t\t<title>GudetamaFrance!</title>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" media=\"screen\" type=\"text/css\" title=\"Design\" href=\"design/style.css\" />\r\n");
      out.write("\t\t<!--[if IE 6]><link rel=\"stylesheet\" media=\"screen\" type=\"text/css\" title=\"Design\" href=\"design/ie6.css\" /> <![endif]-->\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"conteneur_1\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Début du menu horizontal -->\r\n");
      out.write("\t\t\t<ul id=\"MH\">\r\n");
      out.write("\t\t\t\t<li><a href=\"index.jsp\">Accueil</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"connexion.jsp\">Connexion</a></li>\r\n");
      out.write("\t\t\t\t<!--<li><a href=\"#\">Menu 3</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">Menu 4</a></li>-->\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<!-- Fin du menu horizontal -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"banniere\"><div id=\"logo\"></div></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"conteneur_2\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"corps\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Début du menu vertical -->\r\n");
      out.write("\t\t\t\t\t<div id=\"MV\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"en_tete_MV\">Séries</div>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"lien_MV\" href=\"video1.jsp\">Noël 2016</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"lien_MV\">Eté 2016</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"lien_MV\">Noël 2015</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"lien_MV\">Eté 2015</a>\r\n");
      out.write("\t\t\t\t\t\t\t<!--<a class=\"lien_MV\">Menu 5</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"lien_MV\">Menu 6</a>-->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bottom_MV\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"marge_MV\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"en_tete_MV\">Autres</div>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"lien_MV\">Nouveautés</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"lien_MV\">Fan pages</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"lien_MV\">Qui sommes-nous</a>\r\n");
      out.write("\t\t\t\t\t\t\t<!--<a class=\"lien_MV\">Menu 4</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"lien_MV\">Menu 5</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"lien_MV\">Menu 6</a>-->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bottom_MV\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"marge_MV\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- Fin du menu vertical -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"texte\"><div id=\"overflow\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Début de la zone de texte -->\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\tIl s'appelle Gudetama, et c'est l'un des personnages de la société Sanrio, à qui l'on doit Hello Kitty.</br>\r\n");
      out.write("\t\t\t\t\t\t愛 Flasque, jaune, endormi, Gudetama est en fait un étrange ouf flemmard inventé l'année dernière et dont le seul but est de ne rien faire de la journée et de se morfondre dans son blanc d'oeuf :D\r\n");
      out.write("\t\t\t\t\t\t<!--Votre design est enfin prêt à être utilisé. Ouvrez cette page avec un éditeur de texte afin de la modifier à votre convenance.\r\n");
      out.write("\t\t\t\t\t\tSi vous ne parvenez pas à modifier votre design comme vous le voudriez, nous vous conseillons de suivre \r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.creer-son-website.fr/tutoriel.php\">ce tutoriel</a>.\r\n");
      out.write("\t\t\t\t\t\tVous pouvez également poser des questions aux autres membres sur <a href=\"http://www.creer-son-website.fr/forum.php\">le forum</a> en cas de problème.\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\tSi vous le désirez, il vous est possible de continuer à travailler votre design en le \r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.creer-son-website.fr/chargement_kit.php?clef=PDKDV\">rechargeant</a>.\r\n");
      out.write("\t\t\t\t\t\tLes designs créés avec Générakit sont sous license Créative Commons, et sont par conséquent soumis aux règles que nous rappelons ici.\r\n");
      out.write("\t\t\t\t\t\tVous avez le droit de modifier manuellement votre design après son téléchargement afin de l'adapter à vos besoin et de vous en servir pour votre site.\r\n");
      out.write("\t\t\t\t\t\tLa signature (lien en bas de page menant vers notre page d'accueil) n'est dans ce cas pas obligatoire, mais est toutefois activée par défaut.\r\n");
      out.write("\t\t\t\t\t\tLa redistribution des designs créés avec Générakit est autorisée, mais vous devez dans ce cas respecter à la lettre les\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.creer-son-website.fr/conditions.php\">conditions de redistribution</a> imposées. L'administrateur pourra s'il\r\n");
      out.write("\t\t\t\t\t\tle souhaite utiliser et redistribuer intégralement ou partiellement les designs créés, dans le but d'améliorer la qualité du service proposé.\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\tNous vous serions fortement reconnaissants si vous pouviez participer à la vie du <a href=\"http://www.creer-son-website.fr/forum.php\">forum</a> et de la communauté.\r\n");
      out.write("\t\t\t\t\t\tIl est par exemple possible de montrer vos créations aux autres membres, de présenter votre projet et d'obtenir ainsi des conseils pour l'améliorer.\r\n");
      out.write("\t\t\t\t\t\tNous mettons aussi à disposition sur demande des userbars et des bannières pour présenter Générakit sur d'autres forums si vous le désirez.-->\r\n");
      out.write("\t\t\t\t\t\t</p><br />\r\n");
      out.write("\t\t\t\t\t\t<!-- Fin de la zone de texte -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"clear_both\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"pied_de_page\">\r\n");
      out.write("\t\t\t<a href=\"http://www.creer-son-website.fr\">Hey coucou !</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("Entrez ce lien à tout moment dans la barre d'adresse pour recharger votre design :\r\n");
      out.write("http://www.creer-son-website.fr/chargement_kit.php?clef=PDKDV\r\n");
      out.write("-->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
